-- 사용자 테이블
CREATE TABLE users (
    id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    email    VARCHAR2(60) UNIQUE,
    nickname VARCHAR2(30)
);

-- 주문 테이블
-- status 배송상태 
-- > DLIVERED(배송완료)
-- > IN_CART(장바구니에 담긴 상태)
-- created_at 주문 생성 날짜
CREATE TABLE orders (
    id         NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    status     VARCHAR2(15),
    created_at TIMESTAMP,
    user_id    NUMBER
        REFERENCES users ( id )
);

-- 결제 테이블
-- amount 결제된 금액
-- ptype 결제 유형
CREATE TABLE payments (
    id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    amount   NUMBER,
    ptype    VARCHAR2(30),
    order_id NUMBER
        REFERENCES orders ( id )
);

-- 상품 테이블
CREATE TABLE products (
    id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    name  VARCHAR2(60),
    price NUMBER,
    ptype VARCHAR2(15)
);

-- 주문내역 테이블
CREATE TABLE order_details (
    id         NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    order_id   NUMBER
        REFERENCES orders ( id ),
    product_id NUMBER
        REFERENCES products ( id ),
    count      NUMBER
);

-- 사용자
INSERT INTO users (
    email,
    nickname
) VALUES (
    'leeseohee@ying.kr',
    '서희'
);

INSERT INTO users (
    email,
    nickname
) VALUES (
    'kuma@ying.kr',
    '쿠마'
);

INSERT INTO users (
    email,
    nickname
) VALUES (
    'hawk@ying.kr',
    '호크'
);

-- 주문
INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2021-11-12 05:07:12', 'YYYY-MM-DD HH24:MI:SS'),
    1
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2021-11-17 22:14:54', 'YYYY-MM-DD HH24:MI:SS'),
    1
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2021-11-24 19:13:46', 'YYYY-MM-DD HH24:MI:SS'),
    2
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2021-11-29 23:57:29', 'YYYY-MM-DD HH24:MI:SS'),
    3
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2021-12-06 22:25:13', 'YYYY-MM-DD HH24:MI:SS'),
    3
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2022-01-02 13:04:25', 'YYYY-MM-DD HH24:MI:SS'),
    2
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2022-01-06 15:45:51', 'YYYY-MM-DD HH24:MI:SS'),
    2
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2022-02-13 17:55:35', 'YYYY-MM-DD HH24:MI:SS'),
    1
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'DELIVERED',
    TO_TIMESTAMP('2022-02-28 17:50:14', 'YYYY-MM-DD HH24:MI:SS'),
    2
);

INSERT INTO orders (
    status,
    created_at,
    user_id
) VALUES (
    'IN_CART',
    TO_TIMESTAMP('2022-03-06 14:54:23', 'YYYY-MM-DD HH24:MI:SS'),
    1
);

-- 결제
INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    33640,
    'SAMSUNG CARD',
    1
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    33110,
    'SAMSUNG CARD',
    2
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    31200,
    'LOTTE CARD',
    3
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    69870,
    'KAKAO PAY',
    4
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    32800,
    'KAKAO PAY',
    5
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    42210,
    'LOTTE CARD',
    6
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    46060,
    'LOTTE CARD',
    7
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    42520,
    'SAMSUNG CARD',
    8
);

INSERT INTO payments (
    amount,
    ptype,
    order_id
) VALUES (
    23070,
    'LOTTE CARD',
    9
);

-- 상품
INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '돈까스 8입 1kg',
    12900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '우유 900mL',
    1970,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '채소 믹스 500g',
    4990,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '참치마요 120g',
    4400,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '돼지 프랑크 360g',
    3900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '달걀감자 샐러드 500g',
    6900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '달걀듬뿍 샐러드 500g',
    6900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '크림치즈',
    2180,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '김자반 볶음 50g + 50g',
    3000,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '신라면 멀티 5봉',
    3680,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '우유식빵',
    2900,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '야채참치 100g',
    1590,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '고추참치 85g 8캔',
    10800,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '간편 양배추 280g',
    2200,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '샐러드 키트 6봉',
    8900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '직화구이 햄',
    2990,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '비앤나 소시지 800g',
    6900,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '무항생제 특란 20구',
    7200,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '나가사키짬뽕 5입',
    4480,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '수제 크림치즈 200g',
    9000,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '한돈 떡갈비',
    3100,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '플레인 베이글',
    1300,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '노브랜드 리얼 햄 1kg',
    7380,
    '냉장 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '짜파게티 멀티 5봉',
    3680,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '짜왕 멀티 4봉',
    5300,
    '상온 식품'
);

INSERT INTO products (
    name,
    price,
    ptype
) VALUES (
    '노브랜드 짜장라면 멀티 4봉',
    2280,
    '상온 식품'
);

-- 주문내역
INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    1,
    22,
    6
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    1,
    20,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    1,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    1,
    1,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    2,
    2,
    3
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    2,
    20,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    2,
    11,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    2,
    21,
    4
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    18,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    19,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    10,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    20,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    3,
    11,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    15,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    7,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    1,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    9,
    4
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    12,
    6
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    16,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    17,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    4,
    11,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    5,
    11,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    5,
    20,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    5,
    14,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    5,
    15,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    5,
    7,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    10,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    3,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    1,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    6,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    7,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    6,
    11,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    4,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    12,
    10
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    13,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    14,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    2,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    3,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    7,
    11,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    8,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    5,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    11,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    1,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    6,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    8,
    7,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    9,
    11,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    9,
    4,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    9,
    2,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    9,
    6,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    9,
    7,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    10,
    1,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    10,
    2,
    2
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    10,
    5,
    1
);

INSERT INTO order_details (
    order_id,
    product_id,
    count
) VALUES (
    10,
    8,
    1
);

COMMIT;
-- 서희의 모든 주문 목록 조회
SELECT
    u.nickname   AS 주문자,
    o.id         AS 주문번호,
    o.status     AS 주문상태,
    o.created_at AS 주문일자
FROM
         orders o
    JOIN users u ON ( u.id = o.user_id )
WHERE
    u.nickname = '서희';

-- 서희가 주문한 모든 횟수 조회
SELECT
    COUNT(*) AS 주문횟수
FROM
         orders o
    JOIN users u ON ( u.id = o.user_id )
WHERE
    u.nickname = '서희';

-- 서희의 모든 주문별 결제 금액 조회
-- 주문자명    주문번호    결제금액
-- 서희	      1		    33640
-- 서희       2          33110
-- 서희       8          42520
-- 서희       10         null
SELECT
    u.nickname AS 주문자명,
    o.id       AS 주문번호,
    p.amount   AS 결제금액
FROM
         orders o
    JOIN users    u ON ( o.user_id = u.id )
    JOIN payments p ON ( o.id = p.order_id )
WHERE
    u.nickname = '서희';

-- 서희의 총 결제 금액 조회
SELECT
    SUM(p.amount) AS 결제금액
FROM
         orders o
    JOIN users    u ON ( o.user_id = u.id )
    JOIN payments p ON ( o.id = p.order_id )
WHERE
    u.nickname = '서희';

-- 상품1 돈까스의 총 판매 금액 64,500원 조회
SELECT
    SUM(p.price) as 총판매금액
FROM
         order_details d
    JOIN products p ON ( d.product_id = p.id )
WHERE
        p.id = 1;
        
-- 그룹화
--  데이터를 특징 별로 분류하여, 이를 기준으로 분석하는 기법

select * from payments;
-- 결제(payments) 테이블을 결제 방법에 따라 분류하고, 각각의 결제횟수를 조회하시오.
SELECT
    ptype    AS 결제사,
    COUNT(*) AS "결제 횟수"
FROM
    payments
GROUP BY
    ptype
ORDER BY
    1;

select * from products;
-- 상품(products) 테이블을 보관 타입에 따라 분류하고, 각각의 상품 개수와 평균 가격을 조회하시오.
select 
    ptype as 보관타입, 
    count(*) as 상품개수,
    to_char(avg(price), '9990.00') as 평균가격
from 
    products
group by 
    ptype;

--  사용자(users)와 주문(orders)테이블을 조인하고, 사용자 닉네임별 배송 완료 주문 수를 조회하시오.
-- 사용자 닉네임       배송 완료 주문 수 
-- 서희			3
-- 호크			2
-- 쿠마			4
SELECT
    u.nickname      AS "사용자 닉네임",
    COUNT(o.id) AS "배송 완료 주문 수"
FROM
         users u
    JOIN orders o ON u.id = o.user_id
WHERE
    o.status = 'DELIVERED'
GROUP BY
    u.nickname;
    
